# Generated by Django 5.2.8 on 2025-11-21 00:12

import Contenedor_Calificaciones.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalificadorTributario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[Contenedor_Calificaciones.validators.validate_rut_chileno])),
                ('fecha_ingreso', models.DateField()),
                ('rol', models.CharField(editable=False, max_length=50)),
            ],
            options={
                'verbose_name': 'Calificador tributario',
                'verbose_name_plural': 'Calificadores tributarios',
                'db_table': 'calificador_tributario',
            },
        ),
        migrations.CreateModel(
            name='JefeEquipo',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[Contenedor_Calificaciones.validators.validate_rut_chileno])),
                ('fecha_ingreso', models.DateField()),
                ('rol', models.CharField(editable=False, max_length=50)),
            ],
            options={
                'verbose_name': 'Jefe de equipo',
                'verbose_name_plural': 'Jefes de equipo',
                'db_table': 'jefe_equipo',
            },
        ),
        migrations.CreateModel(
            name='EquipoCalificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificador', models.ForeignKey(db_column='calificador_tributario_rut', on_delete=django.db.models.deletion.PROTECT, related_name='rel_equipos', to='Contenedor_Calificaciones.calificadortributario')),
            ],
            options={
                'verbose_name': 'Calificador en equipo',
                'verbose_name_plural': 'Calificadores en equipos',
                'db_table': 'equipo_calificador',
            },
        ),
        migrations.CreateModel(
            name='EquipoDeTrabajo',
            fields=[
                ('equipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('calificadores', models.ManyToManyField(help_text='Máximo 5 calificadores por equipo Mas El Jefe de equipo.', related_name='equipos_de_trabajo', through='Contenedor_Calificaciones.EquipoCalificador', to='Contenedor_Calificaciones.calificadortributario')),
                ('jefe_equipo_rut', models.ForeignKey(db_column='jefe_equipo_rut', on_delete=django.db.models.deletion.PROTECT, to='Contenedor_Calificaciones.jefeequipo')),
            ],
            options={
                'verbose_name': 'Equipo de trabajo',
                'verbose_name_plural': 'Equipos de trabajo',
                'db_table': 'equipo_de_trabajo',
            },
        ),
        migrations.AddField(
            model_name='equipocalificador',
            name='equipo',
            field=models.ForeignKey(db_column='equipo_id', on_delete=django.db.models.deletion.PROTECT, related_name='rel_calificadores', to='Contenedor_Calificaciones.equipodetrabajo'),
        ),
        migrations.AlterUniqueTogether(
            name='equipocalificador',
            unique_together={('equipo', 'calificador')},
        ),
    ]
