# Generated by Django 5.2.7 on 2025-11-21 18:57

import Contenedor_Calificaciones.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenedor_Calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.AlterField(
            model_name='equipocalificador',
            name='calificador',
            field=models.ForeignKey(db_column='calificador_tributario_rut', on_delete=django.db.models.deletion.PROTECT, related_name='rel_equipos', to='Contenedor_Calificaciones.calificadortributario', unique=True),
        ),
        migrations.AlterField(
            model_name='equipodetrabajo',
            name='jefe_equipo_rut',
            field=models.OneToOneField(db_column='jefe_equipo_rut', on_delete=django.db.models.deletion.PROTECT, to='Contenedor_Calificaciones.jefeequipo'),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[Contenedor_Calificaciones.validators.validate_rut_chileno])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono celular', max_length=25, null=True)),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Formato de correo inválido')])),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('edad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)])),
                ('contrasena', models.CharField(help_text='Debe tener mínimo 8 caracteres, una mayúscula, un número y un símbolo.', max_length=128)),
                ('equipo_trabajo', models.ForeignKey(blank=True, db_column='equipo_trabajdo_id', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='Contenedor_Calificaciones.equipodetrabajo')),
                ('rol', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='Contenedor_Calificaciones.rol')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'db_table': 'cuenta',
            },
        ),
    ]
