# Generated by Django 5.2.7 on 2025-11-21 19:41

import Contenedor_Calificaciones.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenedor_Calificaciones', '0002_rol_alter_equipocalificador_calificador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='rol',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='calificadortributario',
            name='rut',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[Contenedor_Calificaciones.validators.validate_rut_chileno]),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='equipo_trabajo',
            field=models.ForeignKey(blank=True, db_column='equipo_trabajo_id', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='Contenedor_Calificaciones.equipodetrabajo'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='rut',
            field=models.CharField(max_length=13, unique=True, validators=[Contenedor_Calificaciones.validators.validate_rut_chileno]),
        ),
        migrations.AlterField(
            model_name='jefeequipo',
            name='rut',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[Contenedor_Calificaciones.validators.validate_rut_chileno]),
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['rut'], name='idx_cuenta_rut'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
