# Generated by Django 5.2.7 on 2025-11-21 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenedor_Calificaciones', '0003_alter_cuenta_rol_alter_calificadortributario_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipodetrabajo',
            name='jefe_equipo_rut',
            field=models.OneToOneField(blank=True, db_column='jefe_equipo_rut', null=True, on_delete=django.db.models.deletion.PROTECT, to='Contenedor_Calificaciones.jefeequipo'),
        ),
    ]
