# Generated by Django 5.2.7 on 2025-11-21 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenedor_Calificaciones', '0004_alter_equipodetrabajo_jefe_equipo_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipocalificador',
            name='calificador',
            field=models.ForeignKey(db_column='calificador_tributario_rut', on_delete=django.db.models.deletion.PROTECT, related_name='rel_equipos', to='Contenedor_Calificaciones.calificadortributario'),
        ),
    ]
