# Generated by Django 5.2.7 on 2025-11-22 00:05

import Contenedor_Calificaciones.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenedor_Calificaciones', '0005_alter_equipocalificador_calificador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_rut', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[Contenedor_Calificaciones.validators.validate_rut_chileno])),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('ingresado_por_rut', models.CharField(editable=False, max_length=13)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('pais', models.CharField(choices=[('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Peru', 'Perú')], max_length=10)),
                ('tipo_de_empresa', models.CharField(max_length=100)),
                ('ingresado_por', models.ForeignKey(db_column='ingresado_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='Contenedor_Calificaciones.cuenta')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
    ]
