# Generated by Django 5.2.6 on 2025-11-22 21:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenedor_Calificaciones', '0006_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('calificacion_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Calificación')),
                ('metodo_calificacion', models.CharField(choices=[('masiva', 'Masiva'), ('manual', 'Manual')], default='manual', editable=False, max_length=10, verbose_name='Método de Calificación')),
                ('fecha_calculo', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Fecha y hora en que se realizó el cálculo', verbose_name='Fecha de Cálculo')),
                ('estado_calificacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('por_aprobar', 'Por Aprobar'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('eliminado', 'Eliminado'), ('mal_ingresada', 'Mal Ingresada')], default='pendiente', editable=False, max_length=20, verbose_name='Estado de la Calificación')),
                ('nombre_empresa', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Nombre Empresa')),
                ('anio_tributario', models.IntegerField(help_text='Año del periodo tributario', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año Tributario')),
                ('tipo_calificacion', models.CharField(help_text='Tipo o categoría de la calificación tributaria', max_length=100, verbose_name='Tipo de Calificación')),
                ('monto_tributario', models.FloatField(help_text='Monto en valor monetario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Tributario')),
                ('factor_tributario', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Factor Tributario')),
                ('unidad_valor', models.CharField(help_text='Unidad de medida del valor (CLP, UF, USD, etc.)', max_length=50, verbose_name='Unidad de Valor')),
                ('puntaje_calificacion', models.IntegerField(help_text='Puntaje de 0 a 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Puntaje de Calificación')),
                ('categoria_calificacion', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10, verbose_name='Categoría de Calificación')),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=10, verbose_name='Nivel de Riesgo')),
                ('justificacion_resultado', models.TextField(blank=True, help_text='Descripción o justificación de la calificación obtenida', null=True, verbose_name='Justificación del Resultado')),
                ('cuenta_id', models.ForeignKey(db_column='cuenta_id', editable=False, help_text='Usuario que crea la calificación', on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='Contenedor_Calificaciones.cuenta', verbose_name='Cuenta')),
                ('rut_empresa', models.ForeignKey(db_column='empresa_rut', help_text='Empresa a calificar', on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='Contenedor_Calificaciones.empresa', verbose_name='RUT Empresa')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'db_table': 'calificacion_tributaria',
                'ordering': ['-fecha_calculo'],
                'indexes': [models.Index(fields=['anio_tributario'], name='idx_calificacion_anio'), models.Index(fields=['estado_calificacion'], name='idx_calificacion_estado'), models.Index(fields=['-fecha_calculo'], name='idx_calificacion_fecha'), models.Index(fields=['cuenta_id'], name='idx_calificacion_cuenta')],
                'unique_together': {('anio_tributario', 'tipo_calificacion')},
            },
        ),
    ]
