# Generated by Django 5.2.8 on 2025-11-26 00:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenedor_Calificaciones', '0007_calificaciontributaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionAprovada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jefe_rut', models.CharField(max_length=13)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_aprovacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobacion', to='Contenedor_Calificaciones.calificaciontributaria')),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_realizadas', to='Contenedor_Calificaciones.cuenta')),
            ],
            options={
                'verbose_name': 'Calificación Aprovada',
                'verbose_name_plural': 'Calificaciones Aprovadas',
                'db_table': 'calificacion_aprovada',
                'constraints': [models.UniqueConstraint(fields=('calificacion',), name='uniq_aprovacion_por_calificacion')],
            },
        ),
        migrations.CreateModel(
            name='CalificacionRechazada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jefe_rut', models.CharField(max_length=13)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_rechazo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechazo', to='Contenedor_Calificaciones.calificaciontributaria')),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rechazos_realizados', to='Contenedor_Calificaciones.cuenta')),
            ],
            options={
                'verbose_name': 'Calificación Rechazada',
                'verbose_name_plural': 'Calificaciones Rechazadas',
                'db_table': 'calificacion_rechazada',
                'constraints': [models.UniqueConstraint(fields=('calificacion',), name='uniq_rechazo_por_calificacion')],
            },
        ),
    ]
