# Generated by Django 5.2.7 on 2025-11-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenedor_Calificaciones', '0008_calificacionaprovada_calificacionrechazada'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipodetrabajo',
            name='nombre_equipo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nombre del equipo'),
        ),
    ]
