# Generated by Django 5.2.7 on 2025-11-27 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenedor_Calificaciones', '0009_equipodetrabajo_nombre_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipocalificador',
            options={'verbose_name': 'Miembro de equipo', 'verbose_name_plural': 'Miembros de equipo'},
        ),
        migrations.AlterModelOptions(
            name='equipodetrabajo',
            options={},
        ),
        migrations.AlterField(
            model_name='equipocalificador',
            name='calificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contenedor_Calificaciones.calificadortributario'),
        ),
        migrations.AlterField(
            model_name='equipocalificador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contenedor_Calificaciones.equipodetrabajo'),
        ),
        migrations.AlterModelTable(
            name='equipocalificador',
            table=None,
        ),
        migrations.AlterModelTable(
            name='equipodetrabajo',
            table=None,
        ),
    ]
