# Generated by Django 5.2.6 on 2025-11-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenedor_Calificaciones', '0010_alter_equipocalificador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='estado_calificacion',
            field=models.CharField(choices=[('por_enviar', 'Por Enviar'), ('por_aprobar', 'Por Aprobar'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('eliminado', 'Eliminado'), ('mal_ingresada', 'Mal Ingresada')], default='por_enviar', editable=False, max_length=20, verbose_name='Estado de la Calificación'),
        ),
    ]
