# Generated by Django 5.2.6 on 2025-12-04 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenedor_Calificaciones', '0011_alter_calificaciontributaria_estado_calificacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificaciontributaria',
            unique_together=set(),
        ),
    ]
