# Generated by Django 5.2.6 on 2025-12-04 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenedor_Calificaciones', '0012_alter_calificaciontributaria_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_tributario',
            field=models.FloatField(help_text='Valor entre 0 y 1 (Ej: 0.5 = 50%)', validators=[django.core.validators.MinValueValidator(0, message='El factor tributario no puede ser negativo.'), django.core.validators.MaxValueValidator(1, message='El factor tributario debe ser un valor entre 0 y 1.')], verbose_name='Factor Tributario'),
        ),
    ]
